# Generated by Django 5.2.4 on 2025-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("experience_required", models.CharField(max_length=100)),
                ("short_description", models.TextField()),
                ("full_description", models.TextField()),
                ("skills_required", models.JSONField()),
                ("apply_link", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_type"], name="jobs_job_job_typ_f6c220_idx"
                    ),
                    models.Index(
                        fields=["location"], name="jobs_job_locatio_8b2f8c_idx"
                    ),
                    models.Index(fields=["role"], name="jobs_job_role_b56ec0_idx"),
                    models.Index(
                        fields=["company_name"], name="jobs_job_company_8d1ffe_idx"
                    ),
                ],
            },
        ),
    ]
