# Generated by Django 5.2.4 on 2025-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="compensation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                ],
                max_length=20,
            ),
        ),
    ]
